---
name: 'Get last commit message for synchronize event'
on:
  workflow_call:
    outputs:
      msg:
        description: "Last commit message from Synchronize event"
        value: ${{ jobs.git.outputs.msg }}

runs:
  git:
    runs-on: ubuntu-latest
    if: "github.event_name == 'synchronize'"
    outputs:
      msg: ${{ steps.set.outputs.msg }}
    steps:
      - name: Checkout repository ðŸ›Ž
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.after }}

      - name: Set commit message ðŸ“
        id: set
        run: |
          echo "msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
