---
name: Check Spelling ğŸ†

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: spelling-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  git:
    name: Set commit message ğŸ“
    runs-on: ubuntu-latest
    outputs:
      msg: ${{ steps.set.outputs.msg }}
    steps:
      - name: Checkout repository ğŸ›
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.after }}

      - name: Set commit message ğŸ“
        id: set
        run: |
          echo "{msg}={$(git log -1 --pretty=%B)}" >> $GITHUB_OUTPUT

  spelling:
    name: Run Spellcheck ğŸ” 
    runs-on: ubuntu-latest
    needs: git
    if: |
      !(contains(github.event.commits[0].message, '[skip spellcheck]') ||
        contains(github.event.head_commit.message, '[skip spellcheck]') ||
        contains(needs.git.outputs.msg, '[skip spellcheck]')
      )
    steps:
      - name: Checkout repository ğŸ›
        uses: actions/checkout@v4

      - name: Setup R ğŸ“Š
        uses: r-lib/actions/setup-r@v2

      - name: Install R package dependencies ğŸ“¦
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::spelling

      - name: Run Spellcheck ğŸ‘Ÿ
        uses: insightsengineering/r-spellcheck-action@v3
        with:
          exclude: data/*,**/*.Rd,**/*.md,*.md
          additional_options: ""
